
import { TranslationSchema, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationSchema> = {
  ar: {
    title: "الميزان",
    home: "الرئيسية",
    metals: "المعادن",
    currencies: "العملات",
    goldOunce: "أونصة الذهب",
    silverOunce: "أونصة الفضة",
    gold24: "عيار 24",
    gold21: "عيار 21",
    gold18: "عيار 18",
    gold21Syp: "غرام 21 سوري",
    usdTry: "دولار / ليرة تركية",
    usdEur: "دولار / يورو",
    usdSyp: "الدولار مقابل السورية",
    trySyp: "ليرة تركية / ليرة سورية",
    buy: "شراء",
    sell: "مبيع",
    calculator: "المحول",
    convert: "تحويل",
    amount: "المبلغ / الوزن",
    from: "من",
    to: "إلى",
    result: "النتيجة",
    lastUpdated: "آخر تحديث",
    liveMarket: "تحديث مباشر",
    manualUpdate: "تحديث يدوي",
    history: "السجل التاريخي",
    period1d: "يوم",
    period1w: "أسبوع",
    period1m: "شهر",
    period1y: "سنة",
    periodAll: "الكل",
    portfolio: "المحفظة",
    addPortfolio: "إضافة للمحفظة",
    totalPortfolio: "إجمالي قيمة المحفظة",
    weight: "الوزن (غرام)",
    purity: "العيار",
    currencyLabel: "العملة",
    delete: "حذف",
    emptyPortfolio: "المحفظة فارغة حالياً",
    manualOunce: "سعر الأونصة اليدوي ($)",
    manualSyp: "سعر الدولار/سوري اليدوي",
    cancel: "إلغاء",
    edit: "تفعيل",
    about: "حول التطبيق"
  },
  en: {
    title: "Mizan",
    home: "Home",
    metals: "Metals",
    currencies: "Currencies",
    goldOunce: "Gold Ounce",
    silverOunce: "Silver Ounce",
    gold24: "24K Gold",
    gold21: "21K Gold",
    gold18: "18K Gold",
    gold21Syp: "21K Gram (SYP)",
    usdTry: "USD / TRY",
    usdEur: "USD / EUR",
    usdSyp: "USD vs SYP",
    trySyp: "TRY / SYP",
    buy: "Buy",
    sell: "Sell",
    calculator: "Converter",
    convert: "Convert",
    amount: "Amount / Weight",
    from: "From",
    to: "To",
    result: "Result",
    lastUpdated: "Last Updated",
    liveMarket: "Live Stream",
    manualUpdate: "Manual Update",
    history: "Historical Record",
    period1d: "1D",
    period1w: "1W",
    period1m: "1M",
    period1y: "1Y",
    periodAll: "All",
    portfolio: "Portfolio",
    addPortfolio: "Add to Portfolio",
    totalPortfolio: "Total Portfolio Value",
    weight: "Weight (g)",
    purity: "Purity",
    currencyLabel: "Currency",
    delete: "Delete",
    emptyPortfolio: "Portfolio is empty",
    manualOunce: "Manual Ounce Price ($)",
    manualSyp: "Manual USD/SYP Price",
    cancel: "Cancel",
    edit: "Apply",
    about: "About"
  }
};
